/**
 * Regression base for C3.
 *
 * The asserted numbers are the error bound S2 declares. If C3's geometry kernel
 * drifts from these, the declared bound is no longer true and the spec's
 * Decision Log entry is stale -- that is what these tests exist to catch, not
 * refactoring noise. Bounds are set a little above the measured values so a
 * meaningless last-digit change does not fail the suite, and the measured values
 * are recorded in the comments next to each bound.
 *
 * The coefficient table is loaded from src/coefficients.ts (generated by
 * `npm run fit`), not recomputed, so these tests pin the shipped table.
 */

import { describe, expect, it } from 'vitest';
import { CANDIDATES, RSUP_NK, candidateById, fieldGradient, rsupn } from '../src/candidates.js';
import { FIGMA_TABLES, RSUP_NK_GENERATED } from '../src/coefficients.js';
import { coeffAt, type FitRow } from '../src/fit.js';
import { measure } from '../src/metrics.js';
import { agg, specsFor, sweep, type Row } from '../src/sweep.js';
import { cornerParams, type ShapeSpec } from '../src/contour.js';

const tables: Record<string, FitRow[]> = Object.fromEntries(
  Object.entries(FIGMA_TABLES).map(([id, rows]) => [
    id,
    rows.map((r) => ({ sEff: r.sEff, coeff: r.coeff, contourDevPerR: r.devPerR })),
  ])
);

/** A representative slice of the full S2 matrix, small enough for `pnpm test`. */
const SLICE: ShapeSpec[] = [];
for (const s of [0, 0.2, 0.4, 0.6, 0.8, 1.0]) {
  SLICE.push(specsFor(32, 1, 0.15, s));
  SLICE.push(specsFor(120, 3, 0.15, s));
  SLICE.push(specsFor(600, 1, 0.15, s));
  SLICE.push(specsFor(64, 8, 0.3, s));
  SLICE.push(specsFor(320, 1, 0.5, s)); // capsule limit
}

let cache: Row[] | null = null;
const rows = () => (cache ??= sweep(tables, CANDIDATES, SLICE));

describe('coefficient table integrity', () => {
  it('was generated with the basis order the code is compiled for', () => {
    expect(RSUP_NK).toBe(RSUP_NK_GENERATED);
  });

  it('covers the whole smoothing range with the right coefficient count', () => {
    for (const c of CANDIDATES) {
      const t = FIGMA_TABLES[c.id];
      expect(t, c.id).toBeDefined();
      expect(t[0].sEff).toBe(0);
      expect(t[t.length - 1].sEff).toBe(1);
      for (const r of t) expect(r.coeff.length, c.id).toBe(c.nCoeff);
    }
  });

  it('is monotone in smoothing for the analytic box, whose error can only grow', () => {
    // Family A has one degree of freedom and no corner shaping, so its contour
    // deviation must rise monotonically as the corner departs from a circle.
    let prev = -1;
    for (const r of FIGMA_TABLES['roundbox']) {
      expect(r.devPerR).toBeGreaterThanOrEqual(prev - 1e-12);
      prev = r.devPerR;
    }
  });
});

describe('properties every family holds by construction', () => {
  it('is exact along the straight edges', () => {
    // The corner algebra is gated on max(q, 0), so away from the corners the
    // field must reduce to the exact half-plane distance for every family.
    const spec: ShapeSpec = { W: 100, H: 40, r: 12, smoothing: 0.7 };
    for (const c of CANDIDATES) {
      const prep = c.prepare(spec, coeffAt(tables[c.id], cornerParams(spec).smoothingEff));
      for (const y of [0, 5, 10, 15]) {
        for (const dx of [-8, -3, 0, 3, 8]) {
          const got = c.evalAt(prep, spec.W + dx, y);
          expect(got, `${c.id} at (${spec.W + dx},${y})`).toBeCloseTo(dx, 9);
        }
      }
    }
  });

  it('is exact at smoothing 0 -- the plain circular rounded rectangle', () => {
    for (const c of CANDIDATES) {
      const r = measure(c, specsFor(120, 3, 0.15, 0), coeffAt(tables[c.id], 0));
      for (const b of r.bands) {
        expect(b.valueMax, `${c.id} band ${b.half}`).toBeLessThan(1e-9);
      }
    }
  });

  it('is exact at the capsule limit for every requested smoothing', () => {
    // r == the budget forces effective smoothing to 0, so a capsule is a true
    // stadium and no family is approximating anything.
    for (const s of [0, 0.4, 1.0]) {
      const spec = specsFor(120, 8, 0.5, s);
      expect(cornerParams(spec).smoothingEff).toBeCloseTo(0, 12);
      for (const c of CANDIDATES) {
        const r = measure(c, spec, coeffAt(tables[c.id], 0));
        const b = r.bands.find((x) => x.half === 8)!;
        expect(b.valueMax, `${c.id} s=${s}`).toBeLessThan(1e-9);
      }
    }
  });

  it('has a continuous field across the corner-sector boundary', () => {
    // The sector boundary is where q.y crosses 0. A jump there would read as a
    // hard seam in the rim, so it must be continuous even though the algebra
    // switches branch.
    const spec: ShapeSpec = { W: 80, H: 50, r: 16, smoothing: 0.75 };
    for (const c of CANDIDATES) {
      const prep = c.prepare(spec, coeffAt(tables[c.id], cornerParams(spec).smoothingEff));
      const yBoundary = spec.H - prep.re;
      for (const x of [spec.W - 4, spec.W, spec.W + 4]) {
        const below = c.evalAt(prep, x, yBoundary - 1e-7);
        const above = c.evalAt(prep, x, yBoundary + 1e-7);
        expect(Math.abs(above - below), `${c.id} at x=${x}`).toBeLessThan(1e-5);
      }
    }
  });
});

describe('declared error bound (family D rsupn)', () => {
  it('holds the value bound in each band', () => {
    const mine = rows().filter((r) => r.candId === 'rsupn');
    // measured on this slice: 0.1663 / 0.1663 / 0.1697 px
    expect(agg(mine, 1).valueMax).toBeLessThan(0.2);
    expect(agg(mine, 4).valueMax).toBeLessThan(0.2);
    expect(agg(mine, 8).valueMax).toBeLessThan(0.2);
    // p95 measured 0.1415 / 0.1503 / 0.1556 px
    expect(agg(mine, 8).valueP95).toBeLessThan(0.18);
  });

  it('holds the gradient-direction bound in each band', () => {
    const mine = rows().filter((r) => r.candId === 'rsupn');
    // measured 1.545 / 2.622 / 2.914 deg
    expect(agg(mine, 1).gradMaxDeg).toBeLessThan(1.8);
    expect(agg(mine, 4).gradMaxDeg).toBeLessThan(3.0);
    expect(agg(mine, 8).gradMaxDeg).toBeLessThan(3.3);
    expect(agg(mine, 8).gradP95Deg).toBeLessThan(2.9);
  });

  it('reads as a distance field: |grad| stays near 1', () => {
    // The optics divide by nothing, but refraction strength is read off the
    // field's slope, so a field whose gradient magnitude drifts is not usable as
    // a distance even when its zero set is right.
    const mine = rows().filter((r) => r.candId === 'rsupn');
    expect(agg(mine, 8).eikonalMax).toBeLessThan(0.05);
  });

  it('beats every other family on both metrics', () => {
    const best = agg(
      rows().filter((r) => r.candId === 'rsupn'),
      8
    );
    for (const id of ['roundbox', 'superell', 'rsup']) {
      const other = agg(
        rows().filter((r) => r.candId === id),
        8
      );
      expect(best.valueMax, `value vs ${id}`).toBeLessThan(other.valueMax);
      expect(best.gradMaxDeg, `gradient vs ${id}`).toBeLessThan(other.gradMaxDeg);
    }
  });

  it('the |grad| normalization is what earns family D its margin', () => {
    // C and D share a zero level set and a coefficient table; D differs only by
    // the first-order normalization. If that stops paying for itself, drop it.
    const c = agg(
      rows().filter((r) => r.candId === 'rsup'),
      8
    );
    const d = agg(
      rows().filter((r) => r.candId === 'rsupn'),
      8
    );
    expect(d.valueMax).toBeLessThan(c.valueMax * 0.6);
  });

  it('the plain analytic rounded box misses by more than a pixel', () => {
    // Recorded because it is the reason this spike exists: the field every
    // existing web glass demo ships is not good enough at vitrea's radii.
    const a = agg(
      rows().filter((r) => r.candId === 'roundbox'),
      8
    );
    expect(a.valueMax).toBeGreaterThan(1.0);
  });
});

describe('coefficients survive interpolation off the fit grid', () => {
  it('holds the bound where the budget clamp lands s_eff between table rows', () => {
    // Real shapes rarely have s_eff exactly on the fit grid: the budget clamp
    // produces arbitrary values. Interpolating the table must not degrade the
    // bound, or the table needs to be denser.
    const specs: ShapeSpec[] = [
      { W: 60, H: 21, r: 13, smoothing: 1.0 }, // s_eff = 21/13 - 1 = 0.6154
      { W: 200, H: 33, r: 19, smoothing: 0.9 }, // s_eff = 33/19 - 1 = 0.7368
      { W: 45, H: 45, r: 26, smoothing: 1.0 }, // s_eff = 45/26 - 1 = 0.7308
    ];
    for (const spec of specs) {
      const sEff = cornerParams(spec).smoothingEff;
      expect(FIGMA_TABLES['rsupn'].some((r) => Math.abs(r.sEff - sEff) < 1e-6)).toBe(false);
      const r = measure(rsupn, spec, coeffAt(tables['rsupn'], sEff));
      const b = r.bands.find((x) => x.half === 8)!;
      expect(b.valueMax, `s_eff=${sEff.toFixed(4)}`).toBeLessThan(0.25);
      expect(b.gradMaxDeg, `s_eff=${sEff.toFixed(4)}`).toBeLessThan(3.5);
    }
  });
});

describe('concentric derivation (thickness channel)', () => {
  it('an inset level set is as accurate as the band error at that depth', () => {
    // The spec derives a concentric shape as a level-set offset of the parent
    // field. That makes the inner contour's accuracy exactly the field's error
    // at d = -thickness, so C3 needs no separate bound -- it reads this one.
    const spec: ShapeSpec = { W: 90, H: 60, r: 20, smoothing: 0.6 };
    const res = measure(rsupn, spec, coeffAt(tables['rsupn'], cornerParams(spec).smoothingEff), {
      band: { halfBand: 8, offsets: 33, minPerCurve: 256, perPxStraight: 0.5 },
    });
    for (const b of res.bands) {
      expect(b.valueMax, `inset up to ${b.half}px`).toBeLessThan(0.2);
    }
  });
});

describe('field gradient measurement is sound', () => {
  it('recovers the exact normal where the field is exact', () => {
    // At smoothing 0 every family is exact, so any gradient error here is the
    // measurement's own noise floor rather than a family's error.
    const spec = specsFor(120, 1, 0.15, 0);
    const r = measure(rsupn, spec, coeffAt(tables['rsupn'], 0));
    expect(r.bands.find((b) => b.half === 8)!.gradMaxDeg).toBeLessThan(0.05);
  });

  it('flags C1 kinks rather than reporting them as gradient error', () => {
    // The box branch has interior seams where max(q.x, q.y) switches. Those are
    // real C1 kinks; central differences across them are meaningless, so they
    // are detected and excluded from the gradient statistics.
    const spec: ShapeSpec = { W: 30, H: 30, r: 9, smoothing: 0.5 };
    const prep = rsupn.prepare(spec, coeffAt(tables['rsupn'], cornerParams(spec).smoothingEff));
    // on the diagonal seam of the box branch, deep inside
    const g = fieldGradient(rsupn, prep, 2, 2, 0.02);
    expect(g.kink).toBe(true);
    // and not on a clean exterior point
    const clean = fieldGradient(rsupn, prep, spec.W + 3, 4, 0.02);
    expect(clean.kink).toBe(false);
    expect(clean.mag).toBeCloseTo(1, 6);
  });

  void candidateById;
});
