/**
 * GENERATED by `npm run fit` -- do not edit by hand.
 *
 * Chebyshev (L-inf) coefficient tables for the candidate pseudo-SDF families,
 * indexed by EFFECTIVE corner smoothing (after Figma's rounding-and-smoothing
 * budget clamp). `devPerR` is the max |field| on the true contour in units of
 * the corner radius -- i.e. the family's contour deviation, which is scale-free.
 *
 * Committed so that C3 has a fixed regression target. Regenerate only
 * deliberately, and expect test bounds to move with it.
 *
 * RSUP_NK at generation time: 5
 */

export const RSUP_NK_GENERATED = 5;

export interface CoeffRow {
  sEff: number;
  coeff: number[];
  devPerR: number;
}

/** Fits against Figma's corner family, per effective smoothing. */
export const FIGMA_TABLES: Record<string, CoeffRow[]> = {
  "roundbox": [
    {
      "sEff": 0,
      "coeff": [
        1
      ],
      "devPerR": 4.55191e-15
    },
    {
      "sEff": 0.05,
      "coeff": [
        1.00021187
      ],
      "devPerR": 0.0000877597
    },
    {
      "sEff": 0.1,
      "coeff": [
        1.00083082
      ],
      "devPerR": 0.000344136
    },
    {
      "sEff": 0.15,
      "coeff": [
        1.00183346
      ],
      "devPerR": 0.000759445
    },
    {
      "sEff": 0.2,
      "coeff": [
        1.00319819
      ],
      "devPerR": 0.00132474
    },
    {
      "sEff": 0.25,
      "coeff": [
        1.00490487
      ],
      "devPerR": 0.00203166
    },
    {
      "sEff": 0.3,
      "coeff": [
        1.00693454
      ],
      "devPerR": 0.00287238
    },
    {
      "sEff": 0.35,
      "coeff": [
        1.00926916
      ],
      "devPerR": 0.00383941
    },
    {
      "sEff": 0.4,
      "coeff": [
        1.01189143
      ],
      "devPerR": 0.00492559
    },
    {
      "sEff": 0.45,
      "coeff": [
        1.01478464
      ],
      "devPerR": 0.006124
    },
    {
      "sEff": 0.5,
      "coeff": [
        1.01793335
      ],
      "devPerR": 0.00742824
    },
    {
      "sEff": 0.55,
      "coeff": [
        1.021321
      ],
      "devPerR": 0.00883145
    },
    {
      "sEff": 0.6,
      "coeff": [
        1.02493291
      ],
      "devPerR": 0.0103276
    },
    {
      "sEff": 0.65,
      "coeff": [
        1.02875362
      ],
      "devPerR": 0.0119101
    },
    {
      "sEff": 0.7,
      "coeff": [
        1.03276869
      ],
      "devPerR": 0.0135732
    },
    {
      "sEff": 0.75,
      "coeff": [
        1.03696241
      ],
      "devPerR": 0.0153103
    },
    {
      "sEff": 0.8,
      "coeff": [
        1.04132212
      ],
      "devPerR": 0.0171162
    },
    {
      "sEff": 0.85,
      "coeff": [
        1.04583098
      ],
      "devPerR": 0.0189838
    },
    {
      "sEff": 0.9,
      "coeff": [
        1.05047553
      ],
      "devPerR": 0.0209076
    },
    {
      "sEff": 0.95,
      "coeff": [
        1.05524205
      ],
      "devPerR": 0.022882
    },
    {
      "sEff": 1,
      "coeff": [
        1.06011396
      ],
      "devPerR": 0.0249
    }
  ],
  "superell": [
    {
      "sEff": 0,
      "coeff": [
        1,
        2
      ],
      "devPerR": 4.44089e-15
    },
    {
      "sEff": 0.05,
      "coeff": [
        1.00123719,
        2.00342055
      ],
      "devPerR": 0.0000801712
    },
    {
      "sEff": 0.1,
      "coeff": [
        1.00457465,
        2.01264296
      ],
      "devPerR": 0.000294556
    },
    {
      "sEff": 0.15,
      "coeff": [
        1.00968676,
        2.02675573
      ],
      "devPerR": 0.000617724
    },
    {
      "sEff": 0.2,
      "coeff": [
        1.01641229,
        2.0452981
      ],
      "devPerR": 0.00103352
    },
    {
      "sEff": 0.25,
      "coeff": [
        1.02489397,
        2.06853474
      ],
      "devPerR": 0.00152494
    },
    {
      "sEff": 0.3,
      "coeff": [
        1.035998,
        2.09835682
      ],
      "devPerR": 0.00205641
    },
    {
      "sEff": 0.35,
      "coeff": [
        1.05032558,
        2.13604274
      ],
      "devPerR": 0.00259603
    },
    {
      "sEff": 0.4,
      "coeff": [
        1.0685185,
        2.18296726
      ],
      "devPerR": 0.00311263
    },
    {
      "sEff": 0.45,
      "coeff": [
        1.09131698,
        2.24074241
      ],
      "devPerR": 0.00357692
    },
    {
      "sEff": 0.5,
      "coeff": [
        1.11958251,
        2.31127174
      ],
      "devPerR": 0.00396253
    },
    {
      "sEff": 0.55,
      "coeff": [
        1.15435509,
        2.39688986
      ],
      "devPerR": 0.00424732
    },
    {
      "sEff": 0.6,
      "coeff": [
        1.1969203,
        2.50051976
      ],
      "devPerR": 0.00441399
    },
    {
      "sEff": 0.65,
      "coeff": [
        1.24892608,
        2.62594451
      ],
      "devPerR": 0.00445002
    },
    {
      "sEff": 0.7,
      "coeff": [
        1.31253863,
        2.77817097
      ],
      "devPerR": 0.00434774
    },
    {
      "sEff": 0.75,
      "coeff": [
        1.39069346,
        2.96401344
      ],
      "devPerR": 0.00410385
    },
    {
      "sEff": 0.8,
      "coeff": [
        1.4874955,
        3.1930254
      ],
      "devPerR": 0.00371893
    },
    {
      "sEff": 0.85,
      "coeff": [
        1.60887736,
        3.47903386
      ],
      "devPerR": 0.00319697
    },
    {
      "sEff": 0.9,
      "coeff": [
        1.76375566,
        3.84283669
      ],
      "devPerR": 0.00254486
    },
    {
      "sEff": 0.95,
      "coeff": [
        1.96618227,
        4.31723466
      ],
      "devPerR": 0.00177318
    },
    {
      "sEff": 1,
      "coeff": [
        2.23982148,
        4.95756194
      ],
      "devPerR": 0.0009009
    }
  ],
  "rsup": [
    {
      "sEff": 0,
      "coeff": [
        0,
        0,
        0,
        0,
        0
      ],
      "devPerR": 4.55191e-15
    },
    {
      "sEff": 0.05,
      "coeff": [
        0.17229922,
        -0.57843267,
        0.94745447,
        -0.75342668,
        0.23188652
      ],
      "devPerR": 0.0000795723
    },
    {
      "sEff": 0.1,
      "coeff": [
        0.1528229,
        -0.13030581,
        -0.2214859,
        0.42143243,
        -0.18487674
      ],
      "devPerR": 0.000221321
    },
    {
      "sEff": 0.15,
      "coeff": [
        0.08799722,
        0.37596759,
        -1.23860352,
        1.27833243,
        -0.44984249
      ],
      "devPerR": 0.00020311
    },
    {
      "sEff": 0.2,
      "coeff": [
        0.06791092,
        0.43598426,
        -1.06654674,
        0.88960434,
        -0.25815276
      ],
      "devPerR": 0.000314471
    },
    {
      "sEff": 0.25,
      "coeff": [
        0.08568973,
        0.21482387,
        -0.2852117,
        -0.03448269,
        0.10234124
      ],
      "devPerR": 0.000397169
    },
    {
      "sEff": 0.3,
      "coeff": [
        0.12107115,
        -0.10034704,
        0.59290929,
        -0.93110813,
        0.41323529
      ],
      "devPerR": 0.000389318
    },
    {
      "sEff": 0.35,
      "coeff": [
        0.19473757,
        -0.60204839,
        1.74425741,
        -1.96756079,
        0.73790198
      ],
      "devPerR": 0.000396366
    },
    {
      "sEff": 0.4,
      "coeff": [
        0.20633019,
        -0.64612615,
        1.7257626,
        -1.77580066,
        0.60777871
      ],
      "devPerR": 0.000562865
    },
    {
      "sEff": 0.45,
      "coeff": [
        0.20740344,
        -0.60694729,
        1.49567287,
        -1.38229267,
        0.41422845
      ],
      "devPerR": 0.000702136
    },
    {
      "sEff": 0.5,
      "coeff": [
        0.18442027,
        -0.40109927,
        0.87301409,
        -0.61604528,
        0.09728682
      ],
      "devPerR": 0.000741861
    },
    {
      "sEff": 0.55,
      "coeff": [
        0.14433866,
        -0.07398101,
        -0.03198855,
        0.41009473,
        -0.30191682
      ],
      "devPerR": 0.000669581
    },
    {
      "sEff": 0.6,
      "coeff": [
        0.05594672,
        0.55731115,
        -1.59567242,
        2.0268849,
        -0.88947808
      ],
      "devPerR": 0.000540505
    },
    {
      "sEff": 0.65,
      "coeff": [
        0.02895533,
        0.78966635,
        -2.22398983,
        2.69966652,
        -1.13103881
      ],
      "devPerR": 0.000713798
    },
    {
      "sEff": 0.7,
      "coeff": [
        0.00364655,
        0.97120044,
        -2.65963414,
        3.1198731,
        -1.26404382
      ],
      "devPerR": 0.000983567
    },
    {
      "sEff": 0.75,
      "coeff": [
        -0.00900127,
        1.06159349,
        -2.86306846,
        3.29036733,
        -1.30166793
      ],
      "devPerR": 0.00123106
    },
    {
      "sEff": 0.8,
      "coeff": [
        -0.02181546,
        1.13237968,
        -2.9794545,
        3.33958794,
        -1.28583799
      ],
      "devPerR": 0.00137656
    },
    {
      "sEff": 0.85,
      "coeff": [
        0.01079982,
        0.90842707,
        -2.41502297,
        2.7192196,
        -1.03234863
      ],
      "devPerR": 0.00140703
    },
    {
      "sEff": 0.9,
      "coeff": [
        0.02082712,
        0.78785003,
        -2.01122302,
        2.1960281,
        -0.79663302
      ],
      "devPerR": 0.00122131
    },
    {
      "sEff": 0.95,
      "coeff": [
        0.06028054,
        0.48151129,
        -1.18355152,
        1.25863912,
        -0.41464021
      ],
      "devPerR": 0.000863628
    },
    {
      "sEff": 1,
      "coeff": [
        0.10998181,
        0.08963148,
        -0.12832942,
        0.07742006,
        0.05857178
      ],
      "devPerR": 0.000337869
    }
  ],
  "rsupn": [
    {
      "sEff": 0,
      "coeff": [
        0,
        0,
        0,
        0,
        0
      ],
      "devPerR": 4.44089e-15
    },
    {
      "sEff": 0.05,
      "coeff": [
        0.17192786,
        -0.57453584,
        0.93678851,
        -0.74224658,
        0.22784924
      ],
      "devPerR": 0.0000787263
    },
    {
      "sEff": 0.1,
      "coeff": [
        0.15267992,
        -0.12909167,
        -0.22499519,
        0.42555348,
        -0.18655278
      ],
      "devPerR": 0.000220143
    },
    {
      "sEff": 0.15,
      "coeff": [
        0.08481224,
        0.39460055,
        -1.27818536,
        1.3146661,
        -0.46204673
      ],
      "devPerR": 0.000208252
    },
    {
      "sEff": 0.2,
      "coeff": [
        0.06710202,
        0.4426899,
        -1.08444805,
        0.90833394,
        -0.26486554
      ],
      "devPerR": 0.000317781
    },
    {
      "sEff": 0.25,
      "coeff": [
        0.08593485,
        0.21389316,
        -0.284278,
        -0.03442399,
        0.10203143
      ],
      "devPerR": 0.000393427
    },
    {
      "sEff": 0.3,
      "coeff": [
        0.12086127,
        -0.09837148,
        0.58740362,
        -0.92505881,
        0.41092682
      ],
      "devPerR": 0.000384627
    },
    {
      "sEff": 0.35,
      "coeff": [
        0.19195982,
        -0.58065521,
        1.68747114,
        -1.90488976,
        0.71339719
      ],
      "devPerR": 0.00037628
    },
    {
      "sEff": 0.4,
      "coeff": [
        0.20580383,
        -0.64359429,
        1.72183146,
        -1.7735827,
        0.60749205
      ],
      "devPerR": 0.000554941
    },
    {
      "sEff": 0.45,
      "coeff": [
        0.20963391,
        -0.6235343,
        1.53893663,
        -1.42961335,
        0.43272753
      ],
      "devPerR": 0.000696599
    },
    {
      "sEff": 0.5,
      "coeff": [
        0.18345838,
        -0.39738895,
        0.86930065,
        -0.6162596,
        0.09847429
      ],
      "devPerR": 0.000729633
    },
    {
      "sEff": 0.55,
      "coeff": [
        0.15021017,
        -0.10642312,
        0.03456218,
        0.35031318,
        -0.28210743
      ],
      "devPerR": 0.00065723
    },
    {
      "sEff": 0.6,
      "coeff": [
        0.0574571,
        0.54959359,
        -1.57948482,
        2.01134453,
        -0.88391405
      ],
      "devPerR": 0.000533969
    },
    {
      "sEff": 0.65,
      "coeff": [
        0.0290426,
        0.79150557,
        -2.2341988,
        2.71564668,
        -1.13881723
      ],
      "devPerR": 0.000705984
    },
    {
      "sEff": 0.7,
      "coeff": [
        0.00610502,
        0.95536509,
        -2.62411085,
        3.08626749,
        -1.25256664
      ],
      "devPerR": 0.000951783
    },
    {
      "sEff": 0.75,
      "coeff": [
        -0.00912482,
        1.0608592,
        -2.86162189,
        3.29090302,
        -1.30280908
      ],
      "devPerR": 0.00120108
    },
    {
      "sEff": 0.8,
      "coeff": [
        -0.02095565,
        1.12907188,
        -2.97794712,
        3.34408477,
        -1.28941254
      ],
      "devPerR": 0.00134355
    },
    {
      "sEff": 0.85,
      "coeff": [
        0.01389408,
        0.89302668,
        -2.39016784,
        2.70448292,
        -1.03018516
      ],
      "devPerR": 0.00138316
    },
    {
      "sEff": 0.9,
      "coeff": [
        0.01628625,
        0.79606496,
        -2.00469962,
        2.1767657,
        -0.78757687
      ],
      "devPerR": 0.00120458
    },
    {
      "sEff": 0.95,
      "coeff": [
        0.06037106,
        0.48294462,
        -1.1916487,
        1.27094865,
        -0.42038678
      ],
      "devPerR": 0.000843346
    },
    {
      "sEff": 1,
      "coeff": [
        0.10910234,
        0.09555105,
        -0.1426663,
        0.0921919,
        0.05309191
      ],
      "devPerR": 0.000328245
    }
  ]
};

/**
 * Fits against Apple's actual `.continuous` corner. Apple's curve has no
 * smoothing parameter, so this is a single coefficient set. It is ~3x closer to
 * Apple than routing through Figma's family at its best-matching smoothing.
 */
export const APPLE_TABLES: Record<string, { coeff: number[]; devPerR: number }> = {
  "rsup": {
    "coeff": [
      0.05944375,
      0.53352847,
      -1.47723609,
      1.76689797,
      -0.73837656
    ],
    "devPerR": 0.00062355
  },
  "rsupn": {
    "coeff": [
      0.058939,
      0.53608908,
      -1.48273371,
      1.77253595,
      -0.74059491
    ],
    "devPerR": 0.000606381
  }
};

/**
 * The Figma smoothing value that best reproduces Apple's continuous corner --
 * one of the spec's named delegated unknowns, answered numerically.
 * `hausdorffPerR` is the two-sided contour distance in units of the radius.
 */
export const APPLE_BEST_FIGMA_SMOOTHING = {
  radiusFixed: { smoothing: 0.66, hausdorffPerR: 0.00196015 },
  radiusFree: {
    smoothing: 0.6566210937500002,
    radiusScale: 0.99875,
    hausdorffPerR: 0.00174916,
  },
};
