/**
 * Regenerates src/coefficients.ts. Run with `npm run fit`.
 *
 * The coefficient table is committed rather than recomputed at test time: the
 * fit takes about a minute, and C3 needs a fixed table to regress against, not a
 * table that quietly moves whenever the optimizer is touched.
 */

import { writeFileSync } from 'node:fs';
import { CANDIDATES, RSUP_NK, rsup, rsupn } from './candidates.js';
import { FIT_GRID, fitCandidate, fitToReference } from './fit.js';
import { APPLE_REACH, buildAppleContour } from './apple.js';
import { segPoint, type ShapeSpec } from './contour.js';
import { bestFigmaMatch } from './reference.js';

const t0 = Date.now();

const figma: Record<string, { sEff: number; coeff: number[]; devPerR: number }[]> = {};
for (const c of CANDIDATES) {
  process.stderr.write(`fitting ${c.id} against Figma...\n`);
  figma[c.id] = fitCandidate(c, FIT_GRID).map((r) => ({
    sEff: r.sEff,
    coeff: r.coeff.map((x) => Number(x.toFixed(8))),
    devPerR: Number(r.contourDevPerR.toPrecision(6)),
  }));
}

// Apple's own corner, as a direct fit target
process.stderr.write('fitting against Apple...\n');
const appleSpec: ShapeSpec = { W: 64, H: 64, r: 1, smoothing: 0 };
const ac = buildAppleContour(appleSpec);
const applePts: { x: number; y: number }[] = [];
for (const s of ac.segments) {
  const n = s.kind === 'line' ? 8 : 1200;
  for (let i = 0; i <= n; i++) {
    const q = segPoint(s, i / n);
    if (q.x >= -1e-12 && q.y >= -1e-12) applePts.push(q);
  }
}
const apple: Record<string, { coeff: number[]; devPerR: number }> = {};
for (const c of [rsup, rsupn]) {
  const f = fitToReference(c, appleSpec, applePts, APPLE_REACH * appleSpec.r);
  apple[c.id] = {
    coeff: f.coeff.map((x) => Number(x.toFixed(8))),
    devPerR: Number(f.contourDevPerR.toPrecision(6)),
  };
}

process.stderr.write('finding the Figma smoothing that best matches Apple...\n');
const match = bestFigmaMatch(false);
const matchFree = bestFigmaMatch(true);

const body = `/**
 * GENERATED by \`npm run fit\` -- do not edit by hand.
 *
 * Chebyshev (L-inf) coefficient tables for the candidate pseudo-SDF families,
 * indexed by EFFECTIVE corner smoothing (after Figma's rounding-and-smoothing
 * budget clamp). \`devPerR\` is the max |field| on the true contour in units of
 * the corner radius -- i.e. the family's contour deviation, which is scale-free.
 *
 * Committed so that C3 has a fixed regression target. Regenerate only
 * deliberately, and expect test bounds to move with it.
 *
 * RSUP_NK at generation time: ${RSUP_NK}
 */

export const RSUP_NK_GENERATED = ${RSUP_NK};

export interface CoeffRow {
  sEff: number;
  coeff: number[];
  devPerR: number;
}

/** Fits against Figma's corner family, per effective smoothing. */
export const FIGMA_TABLES: Record<string, CoeffRow[]> = ${JSON.stringify(figma, null, 2)};

/**
 * Fits against Apple's actual \`.continuous\` corner. Apple's curve has no
 * smoothing parameter, so this is a single coefficient set. It is ~3x closer to
 * Apple than routing through Figma's family at its best-matching smoothing.
 */
export const APPLE_TABLES: Record<string, { coeff: number[]; devPerR: number }> = ${JSON.stringify(
  apple,
  null,
  2
)};

/**
 * The Figma smoothing value that best reproduces Apple's continuous corner --
 * one of the spec's named delegated unknowns, answered numerically.
 * \`hausdorffPerR\` is the two-sided contour distance in units of the radius.
 */
export const APPLE_BEST_FIGMA_SMOOTHING = {
  radiusFixed: { smoothing: ${match.smoothing}, hausdorffPerR: ${Number(
    match.hausdorffPerR.toPrecision(6)
  )} },
  radiusFree: {
    smoothing: ${matchFree.smoothing},
    radiusScale: ${Number(matchFree.radiusScale.toPrecision(6))},
    hausdorffPerR: ${Number(matchFree.hausdorffPerR.toPrecision(6))},
  },
};
`;

writeFileSync(new URL('./coefficients.ts', import.meta.url), body);
process.stderr.write(`wrote src/coefficients.ts in ${((Date.now() - t0) / 1000).toFixed(1)}s\n`);
