/**
 * Generates bench/f32-check.json: the input for the benchmark's accuracy mode.
 *
 * The f64 `expected` values come from src/candidates.ts, whose `rsupn.evalAt`
 * is a line-for-line mirror of `sd_rsupn` in bench/shaders.wgsl. So the
 * difference the benchmark reports is purely f32 vs f64 rounding of the SAME
 * arithmetic, which is the question ("is f32 precision eating the error
 * budget?") -- not a comparison against true distance, which the sweep in
 * src/ already covers.
 *
 * Points sit on and around the true contour of each shape, at offsets scaled
 * by the corner radius, plus a coarse grid, so the corner sector (where all the
 * interesting arithmetic lives) is densely covered.
 *
 *   npx tsx bench/make-f32-check.ts [outPath]
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildContour, segNormal, segPoint, type ShapeSpec } from '../src/contour.js';
import { roundbox, rsupn, type Prepared } from '../src/candidates.js';
import { fitOne } from '../src/fit.js';

const OUT = process.argv[2] ?? path.join(path.dirname(fileURLToPath(import.meta.url)), 'f32-check.json');

// Half-extents, radius, smoothing. One shape per smoothing regime.
const SPECS: ShapeSpec[] = [
  { W: 96, H: 24, r: 8, smoothing: 0 },      // small pill-ish button, plain arc corner
  { W: 100, H: 100, r: 28, smoothing: 0.5 },  // square card, mid smoothing
  { W: 320, H: 180, r: 48, smoothing: 1 },    // large panel, full smoothing
];

const DELTAS = [-1.5, -0.5, -0.1, -0.01, 0, 0.01, 0.1, 0.5, 1.5];
const T_STEPS = 12;

interface OutShape { half: [number, number]; re: number; k: number[]; spec: ShapeSpec }

const shapes: OutShape[] = [];
const points: { shape: number; p: [number, number] }[] = [];
const expected = { rsupn: [] as number[], roundbox: [] as number[] };

for (const spec of SPECS) {
  const fit = fitOne(rsupn, spec.smoothing);
  const prep = rsupn.prepare(spec, fit.coeff);
  // sd_roundbox in the shader is called with the SAME re, so the CPU reference
  // must be too: this compares arithmetic precision, not corner-offset choice.
  const prepBox: Prepared = { W: prep.W, H: prep.H, re: prep.re, k: [] };
  const si = shapes.length;
  shapes.push({ half: [spec.W, spec.H], re: prep.re, k: prep.k.slice(), spec });
  process.stderr.write(
    `shape ${si}: W=${spec.W} H=${spec.H} r=${spec.r} s=${spec.smoothing} ` +
    `re=${prep.re.toFixed(6)} contourDevPerR=${fit.contourDevPerR.toExponential(3)}\n`
  );

  const push = (x: number, y: number) => {
    if (!Number.isFinite(x) || !Number.isFinite(y)) return;
    points.push({ shape: si, p: [x, y] });
    expected.rsupn.push(rsupn.evalAt(prep, x, y));
    expected.roundbox.push(roundbox.evalAt(prepBox, x, y));
  };

  // band around the true contour
  const contour = buildContour(spec);
  for (const seg of contour.segments) {
    for (let i = 0; i <= T_STEPS; i++) {
      const t = i / T_STEPS;
      const q = segPoint(seg, t);
      const n = segNormal(seg, t);
      if (n.x === 0 && n.y === 0) continue;
      for (const d of DELTAS) push(q.x + n.x * d * spec.r, q.y + n.y * d * spec.r);
    }
  }

  // coarse grid over the first quadrant plus a margin, deep interior included
  const gx = 17, gy = 17;
  for (let i = 0; i <= gx; i++) {
    for (let j = 0; j <= gy; j++) {
      push((i / gx) * (spec.W + 2 * spec.r), (j / gy) * (spec.H + 2 * spec.r));
    }
  }
}

const doc = {
  note:
    'Generated by bench/make-f32-check.ts. `expected` is f64 evaluation of the same ' +
    'arithmetic as bench/shaders.wgsl, from src/candidates.ts. Points are shape-local.',
  shapes: shapes.map((s) => ({ half: s.half, re: s.re, k: s.k, spec: s.spec })),
  points,
  expected,
};

fs.writeFileSync(OUT, JSON.stringify(doc));
process.stderr.write(`wrote ${OUT}: ${shapes.length} shapes, ${points.length} points\n`);
