/**
 * The fitted corner-correction coefficient tables. TRANSCRIBED FROM S2, not
 * recomputed — and deliberately so.
 *
 * Source: `spikes/s2-geometry-field/src/coefficients.ts`, itself generated by
 * that spike's `npm run fit`. The fit is an exact Chebyshev (L-inf) solve, not a
 * general optimizer: pinning the corner offset to the true corner reach makes
 * the objective linear in the coefficients, and the residual equioscillates
 * across 11 alternating extrema. The reported deviation is therefore the
 * family's capability rather than an optimizer's luck.
 *
 * These stay committed for the reason S2 gives: a table that silently moves when
 * the fitter is touched is not a regression target. `test/error-bound.test.ts`
 * asserts the declared bound against this table, so regenerating it means
 * re-deriving the bound and updating the spec's Decision Log.
 *
 * Two tables, because there are two reference curves and S2 measured that the
 * choice between them matters 6.4x more than the field family does:
 *
 *  - `FIGMA_RSUPN_TABLE` — indexed by EFFECTIVE smoothing (after the budget
 *    clamp) across the whole [0, 1] range. This is the interpolable authoring
 *    axis, and the axis the declared bound is measured on.
 *  - `APPLE_RSUPN` — one coefficient set, fit directly against Apple's measured
 *    `.continuous` corner. `profile: "continuous"` resolves to this
 *    (Decision Log #20: routing through Figma at smoothing 0.66 was measured and
 *    rejected at 6.4x the value error).
 *
 * Families C (`rsup`) and D (`rsupn`) share a zero level set and are fit
 * separately only because the normalization shifts the L-inf optimum slightly.
 */

/**
 * Number of correction terms. The basis is `s2^2 .. s2^(N+1)` where
 * `s2 = sin(2*theta)`.
 *
 * Starting at the SQUARE is not arbitrary: the true radial support has
 * `R'(0) = 0`, because the corner leaves the straight edge both tangentially and
 * with zero curvature, so any basis with a linear term in `s2` would have to
 * cancel it. Odd powers above that are included because `R` is not an even
 * function of theta about 0 — a `sin^2`-only basis converges visibly more
 * slowly.
 *
 * Order is a tuning knob, not a design commitment. Five terms give 1.38e-3 r
 * worst case with coefficients bounded by 3.3. Seven give 6.6e-4 r but push
 * coefficients to ~56, which starts to matter in f32 — at which point the
 * polynomial wants re-expressing in a Chebyshev basis rather than monomials.
 */
export const RSUP_BASIS_ORDER = 5;

export type CornerCoefficients = readonly [number, number, number, number, number];

export const ZERO_COEFFICIENTS: CornerCoefficients = [0, 0, 0, 0, 0];

export interface CoefficientRow {
  /** effective smoothing, after the budget clamp */
  readonly sEff: number;
  readonly k: CornerCoefficients;
  /** max |field| on the true contour in units of the corner radius — scale-free */
  readonly contourDevPerR: number;
}

/**
 * Family D (`rsupn`) against the Figma corner family, per effective smoothing.
 *
 * The row at `sEff: 0` is exactly zero rather than the fitter's 1e-13 residue,
 * so `smoothing: 0` is a plain circular rounded rectangle to the last bit — an
 * exactness property the suite asserts rather than approximates.
 */
export const FIGMA_RSUPN_TABLE: readonly CoefficientRow[] = [
  { sEff: 0, k: [0, 0, 0, 0, 0], contourDevPerR: 4.44089e-15 },
  { sEff: 0.05, k: [0.17192786, -0.57453584, 0.93678851, -0.74224658, 0.22784924], contourDevPerR: 0.0000787263 },
  { sEff: 0.1, k: [0.15267992, -0.12909167, -0.22499519, 0.42555348, -0.18655278], contourDevPerR: 0.000220143 },
  { sEff: 0.15, k: [0.08481224, 0.39460055, -1.27818536, 1.3146661, -0.46204673], contourDevPerR: 0.000208252 },
  { sEff: 0.2, k: [0.06710202, 0.4426899, -1.08444805, 0.90833394, -0.26486554], contourDevPerR: 0.000317781 },
  { sEff: 0.25, k: [0.08593485, 0.21389316, -0.284278, -0.03442399, 0.10203143], contourDevPerR: 0.000393427 },
  { sEff: 0.3, k: [0.12086127, -0.09837148, 0.58740362, -0.92505881, 0.41092682], contourDevPerR: 0.000384627 },
  { sEff: 0.35, k: [0.19195982, -0.58065521, 1.68747114, -1.90488976, 0.71339719], contourDevPerR: 0.00037628 },
  { sEff: 0.4, k: [0.20580383, -0.64359429, 1.72183146, -1.7735827, 0.60749205], contourDevPerR: 0.000554941 },
  { sEff: 0.45, k: [0.20963391, -0.6235343, 1.53893663, -1.42961335, 0.43272753], contourDevPerR: 0.000696599 },
  { sEff: 0.5, k: [0.18345838, -0.39738895, 0.86930065, -0.6162596, 0.09847429], contourDevPerR: 0.000729633 },
  { sEff: 0.55, k: [0.15021017, -0.10642312, 0.03456218, 0.35031318, -0.28210743], contourDevPerR: 0.00065723 },
  { sEff: 0.6, k: [0.0574571, 0.54959359, -1.57948482, 2.01134453, -0.88391405], contourDevPerR: 0.000533969 },
  { sEff: 0.65, k: [0.0290426, 0.79150557, -2.2341988, 2.71564668, -1.13881723], contourDevPerR: 0.000705984 },
  { sEff: 0.7, k: [0.00610502, 0.95536509, -2.62411085, 3.08626749, -1.25256664], contourDevPerR: 0.000951783 },
  { sEff: 0.75, k: [-0.00912482, 1.0608592, -2.86162189, 3.29090302, -1.30280908], contourDevPerR: 0.00120108 },
  { sEff: 0.8, k: [-0.02095565, 1.12907188, -2.97794712, 3.34408477, -1.28941254], contourDevPerR: 0.00134355 },
  { sEff: 0.85, k: [0.01389408, 0.89302668, -2.39016784, 2.70448292, -1.03018516], contourDevPerR: 0.00138316 },
  { sEff: 0.9, k: [0.01628625, 0.79606496, -2.00469962, 2.1767657, -0.78757687], contourDevPerR: 0.00120458 },
  { sEff: 0.95, k: [0.06037106, 0.48294462, -1.1916487, 1.27094865, -0.42038678], contourDevPerR: 0.000843346 },
  { sEff: 1, k: [0.10910234, 0.09555105, -0.1426663, 0.0921919, 0.05309191], contourDevPerR: 0.000328245 },
];

/** Family C (`rsup`) against the same family. Same zero level set, own L-inf fit. */
export const FIGMA_RSUP_TABLE: readonly CoefficientRow[] = [
  { sEff: 0, k: [0, 0, 0, 0, 0], contourDevPerR: 4.55191e-15 },
  { sEff: 0.05, k: [0.17229922, -0.57843267, 0.94745447, -0.75342668, 0.23188652], contourDevPerR: 0.0000795723 },
  { sEff: 0.1, k: [0.1528229, -0.13030581, -0.2214859, 0.42143243, -0.18487674], contourDevPerR: 0.000221321 },
  { sEff: 0.15, k: [0.08799722, 0.37596759, -1.23860352, 1.27833243, -0.44984249], contourDevPerR: 0.00020311 },
  { sEff: 0.2, k: [0.06791092, 0.43598426, -1.06654674, 0.88960434, -0.25815276], contourDevPerR: 0.000314471 },
  { sEff: 0.25, k: [0.08568973, 0.21482387, -0.2852117, -0.03448269, 0.10234124], contourDevPerR: 0.000397169 },
  { sEff: 0.3, k: [0.12107115, -0.10034704, 0.59290929, -0.93110813, 0.41323529], contourDevPerR: 0.000389318 },
  { sEff: 0.35, k: [0.19473757, -0.60204839, 1.74425741, -1.96756079, 0.73790198], contourDevPerR: 0.000396366 },
  { sEff: 0.4, k: [0.20633019, -0.64612615, 1.7257626, -1.77580066, 0.60777871], contourDevPerR: 0.000562865 },
  { sEff: 0.45, k: [0.20740344, -0.60694729, 1.49567287, -1.38229267, 0.41422845], contourDevPerR: 0.000702136 },
  { sEff: 0.5, k: [0.18442027, -0.40109927, 0.87301409, -0.61604528, 0.09728682], contourDevPerR: 0.000741861 },
  { sEff: 0.55, k: [0.14433866, -0.07398101, -0.03198855, 0.41009473, -0.30191682], contourDevPerR: 0.000669581 },
  { sEff: 0.6, k: [0.05594672, 0.55731115, -1.59567242, 2.0268849, -0.88947808], contourDevPerR: 0.000540505 },
  { sEff: 0.65, k: [0.02895533, 0.78966635, -2.22398983, 2.69966652, -1.13103881], contourDevPerR: 0.000713798 },
  { sEff: 0.7, k: [0.00364655, 0.97120044, -2.65963414, 3.1198731, -1.26404382], contourDevPerR: 0.000983567 },
  { sEff: 0.75, k: [-0.00900127, 1.06159349, -2.86306846, 3.29036733, -1.30166793], contourDevPerR: 0.00123106 },
  { sEff: 0.8, k: [-0.02181546, 1.13237968, -2.9794545, 3.33958794, -1.28583799], contourDevPerR: 0.00137656 },
  { sEff: 0.85, k: [0.01079982, 0.90842707, -2.41502297, 2.7192196, -1.03234863], contourDevPerR: 0.00140703 },
  { sEff: 0.9, k: [0.02082712, 0.78785003, -2.01122302, 2.1960281, -0.79663302], contourDevPerR: 0.00122131 },
  { sEff: 0.95, k: [0.06028054, 0.48151129, -1.18355152, 1.25863912, -0.41464021], contourDevPerR: 0.000863628 },
  { sEff: 1, k: [0.10998181, 0.08963148, -0.12832942, 0.07742006, 0.05857178], contourDevPerR: 0.000337869 },
];

/**
 * Fits against Apple's actual `.continuous` corner. Apple's curve has no
 * smoothing parameter, so each is a single coefficient set. Measured at
 * 6.06e-4 r contour deviation — ~3x closer to Apple than Figma's best-matching
 * smoothing can get, and 6.4x better on band value error than routing through
 * Figma's family (0.104 px vs 0.670 px).
 *
 * The residual barely improves with a higher-order basis (6.06e-4 -> 6.02e-4 for
 * one extra term), because it is limited by Apple's own 2.4532-degree tangent
 * break rather than by the polynomial. This field is as close to Apple's curve
 * as a smooth field can usefully get.
 */
export const APPLE_RSUPN = {
  k: [0.058939, 0.53608908, -1.48273371, 1.77253595, -0.74059491] as CornerCoefficients,
  contourDevPerR: 0.000606381,
} as const;

export const APPLE_RSUP = {
  k: [0.05944375, 0.53352847, -1.47723609, 1.76689797, -0.73837656] as CornerCoefficients,
  contourDevPerR: 0.00062355,
} as const;

/**
 * Linear interpolation into a coefficient table by effective smoothing.
 *
 * Real shapes rarely land on the fit grid: the budget clamp produces arbitrary
 * effective smoothing. `test/error-bound.test.ts` asserts the bound still holds
 * at off-grid values, which is what says the 0.05 grid is dense enough.
 */
export function coefficientsAt(
  table: readonly CoefficientRow[],
  sEff: number,
): { k: CornerCoefficients; contourDevPerR: number } {
  const first = table[0];
  const last = table[table.length - 1];
  if (first === undefined || last === undefined) {
    throw new Error("empty coefficient table");
  }
  if (sEff <= first.sEff) return { k: first.k, contourDevPerR: first.contourDevPerR };
  if (sEff >= last.sEff) return { k: last.k, contourDevPerR: last.contourDevPerR };

  for (let i = 1; i < table.length; i++) {
    const lo = table[i - 1];
    const hi = table[i];
    if (lo === undefined || hi === undefined) break;
    if (sEff <= hi.sEff) {
      const u = (sEff - lo.sEff) / (hi.sEff - lo.sEff);
      const mix = (j: 0 | 1 | 2 | 3 | 4): number => lo.k[j] + u * (hi.k[j] - lo.k[j]);
      return {
        k: [mix(0), mix(1), mix(2), mix(3), mix(4)],
        contourDevPerR: lo.contourDevPerR + u * (hi.contourDevPerR - lo.contourDevPerR),
      };
    }
  }
  return { k: last.k, contourDevPerR: last.contourDevPerR };
}
